# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traderbro < Formula
  desc "Query analyst predictions and research from TraderBro"
  homepage "https://traderbro.ai"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.0/traderbro_darwin_amd64.tar.gz"
      sha256 "a1539cd7651fc175d5f0713e9a646a2422e150d4236521172d094b364ca1ba9a"

      define_method(:install) do
        bin.install "traderbro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.0/traderbro_darwin_arm64.tar.gz"
      sha256 "7ab85680dd18aadabb78dcc692083477efc7a2518bfb105ced4ae77656274704"

      define_method(:install) do
        bin.install "traderbro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.0/traderbro_linux_amd64.tar.gz"
      sha256 "80ed4d8cdea8c01303357a398452faf0ddc1c0261e53ead2a152aa343a1d3c61"
      define_method(:install) do
        bin.install "traderbro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.0/traderbro_linux_arm64.tar.gz"
      sha256 "743b24e9f2a50f258440f66f9fe78a91175098d30bf0868a17c121f1875f1e5d"
      define_method(:install) do
        bin.install "traderbro"
      end
    end
  end

  test do
    system "#{bin}/traderbro", "--version"
  end
end
