# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traderbro < Formula
  desc "Query analyst predictions and research from TraderBro"
  homepage "https://traderbro.ai"
  version "1.0.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.1/traderbro_darwin_amd64.tar.gz"
      sha256 "881f1e7edc3babded208b8a89c60fb920c3830ce51a82ec68a8e64cff46c319b"

      define_method(:install) do
        bin.install "traderbro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.1/traderbro_darwin_arm64.tar.gz"
      sha256 "49f7e53883ade9f702adcce0f77513c667f2affffea08b01cb8dda639aacd215"

      define_method(:install) do
        bin.install "traderbro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.1/traderbro_linux_amd64.tar.gz"
      sha256 "3d78726bd4177b99e857f27df3b6bd5f334a8aabd54bfced7d2190b499eeb717"
      define_method(:install) do
        bin.install "traderbro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TraderBro/traderbro-cli-binary/releases/download/v1.0.1/traderbro_linux_arm64.tar.gz"
      sha256 "5ad5d1e69a21a542d68005e8771cf890a47b27e2b8210395af930062966dff2b"
      define_method(:install) do
        bin.install "traderbro"
      end
    end
  end

  test do
    system "#{bin}/traderbro", "--version"
  end
end
